// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "5d4c76fd-fe63-42d6-993d-61045ed618f6");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1563975684);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1563975804);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1563975204);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1563975444);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1563975324);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1563975564);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1563976097);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 13926);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contentblocking.introCount", 5);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1563975173);
user_pref("browser.laterrun.bookkeeping.sessionCount", 8);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{24861c59-6a6d-46dd-b8ef-7d8bd18bab19}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1563977923709");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1563979738709");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1563976070396");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1563979670396");
user_pref("browser.search.region", "DE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190720144906");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1563978025");
user_pref("browser.slowStartup.averageTime", 730);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20190720144906");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1563978025);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1563975174488");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "00f7916f756d4918abab2ba85ccce8c5");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Mon, 22 Jul 2019 15:40:26 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1563975685);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190720144906");
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"2200aa2f-e239-40ad-82a7-d694f83739dc\",\"fxmonitor@mozilla.org\":\"57742f12-6bef-4cd2-a5d0-dd0015ad0273\",\"screenshots@mozilla.org\":\"2bea132c-c722-4f6d-8fc9-ae244fe76baf\",\"webcompat-reporter@mozilla.org\":\"31240b80-fb09-4ac3-be52-180901e7fbd8\",\"webcompat@mozilla.org\":\"e797b1e2-dc1f-4a50-8f21-9d19e238cf51\",\"default-theme@mozilla.org\":\"13ae85c2-c917-4463-bb1f-a81405267ec4\",\"google@search.mozilla.org\":\"67c84954-713e-4b31-80d9-79354aa20ae2\",\"amazondotcom@search.mozilla.org\":\"82bb7010-c5fc-4a4c-a2d9-76fb57b51558\",\"bing@search.mozilla.org\":\"4f8de5f5-1096-4387-b248-b1443353e694\",\"ddg@search.mozilla.org\":\"c6a93c82-e681-4a15-bdce-36cc9ff8e16d\",\"ebay@search.mozilla.org\":\"8a3f42f6-e3ba-4601-8f6b-b16693132c9e\",\"twitter@search.mozilla.org\":\"b7f4d5db-04c9-4519-a22e-810d30cb9dce\",\"wikipedia@search.mozilla.org\":\"a7160844-7f26-425c-a483-0c848b938de2\"}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1563975350);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190720144906");
user_pref("media.gmp-manager.lastCheck", 1563975350);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "71a20497-5599-4aad-b5e7-aeb192366f8f");
user_pref("security.sandbox.plugin.tempDirSuffix", "ee085739-1a8d-4112-8cc9-5750621be03d");
user_pref("services.blocklist.pinning.checked", 1563968135);
user_pref("services.settings.clock_skew_seconds", 7075);
user_pref("services.settings.last_etag", "\"1563926412647\"");
user_pref("services.settings.last_update_seconds", 1563968488);
user_pref("services.settings.main.cfr-fxa.last_check", 1563968135);
user_pref("services.settings.main.cfr.last_check", 1563968135);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1563968135);
user_pref("services.settings.main.hijack-blocklists.last_check", 1563968135);
user_pref("services.settings.main.language-dictionaries.last_check", 1563968135);
user_pref("services.settings.main.normandy-recipes.last_check", 1563968135);
user_pref("services.settings.main.onboarding.last_check", 1563968135);
user_pref("services.settings.main.sites-classification.last_check", 1563968135);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1563968135);
user_pref("services.settings.security.onecrl.checked", 1563968135);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1563978025);
user_pref("toolkit.telemetry.cachedClientID", "990e2203-0936-4e75-a709-59489dc4fb54");
user_pref("toolkit.telemetry.previousBuildID", "20190720144906");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
